@badgeur_backend_HostAddress = http://localhost:5159
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6IjRPdDNheStZTWg3K1Y5NHEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3lranFybG5kZG9hZXJseWlsZGFiLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmMzhhNTMyZS04ZmJlLTQwNGEtYjJjZi05NzQ1YzA5NTAzZTMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU5OTE2NjY2LCJpYXQiOjE3NTk5MTMwNjYsImVtYWlsIjoiYW5kcmVqMS5pbGlldnNraUBlcGl0ZWNoLmV1IiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTk5MDk0OTN9XSwic2Vzc2lvbl9pZCI6IjNmOTEyOTNmLTkxOWMtNDVkYS1hMmE1LWNjNzIxNjcxZjlhOSIsImlzX2Fub255bW91cyI6ZmFsc2V9.EHbitIcD3RVaC-ipaIBx0wGzVcOt9oQtq17l6D-4MWw

GET {{badgeur_backend_HostAddress}}/users/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{badgeur_backend_HostAddress}}/users/1
Accept: application/json

###

GET {{badgeur_backend_HostAddress}}/users/1
Accept: application/json

###