name: .NET Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build Docker image
    - name: Build Docker image
      run: docker build -t badgeur-backend:latest .
