name: .NET Backend - Docker Build

on:
  push:
    branches: [ "preprod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: ./backend
      run: docker build -t badgeur-backend -f Dockerfile .